export const NOTE_COLORS = [
  { id: 'white', value: 'bg-white', label: 'Blanco' },
  { id: 'red', value: 'bg-red-400', label: 'Rojo vibrante' },
  { id: 'orange', value: 'bg-orange-400', label: 'Naranja' },
  { id: 'amber', value: 'bg-amber-400', label: 'Ámbar' },
  { id: 'yellow', value: 'bg-yellow-300', label: 'Amarillo' },
  { id: 'lime', value: 'bg-lime-400', label: 'Lima' },
  { id: 'green', value: 'bg-green-400', label: 'Verde' },
  { id: 'emerald', value: 'bg-emerald-400', label: 'Esmeralda' },
  { id: 'teal', value: 'bg-teal-400', label: 'Verde azulado' },
  { id: 'cyan', value: 'bg-cyan-400', label: 'Cian' },
  { id: 'sky', value: 'bg-sky-400', label: 'Cielo' },
  { id: 'blue', value: 'bg-blue-400', label: 'Azul' },
  { id: 'indigo', value: 'bg-indigo-400', label: 'Índigo' },
  { id: 'violet', value: 'bg-violet-400', label: 'Violeta' },
  { id: 'purple', value: 'bg-purple-400', label: 'Morado' },
  { id: 'fuchsia', value: 'bg-fuchsia-400', label: 'Fucsia' },
  { id: 'pink', value: 'bg-pink-400', label: 'Rosa' },
  { id: 'rose', value: 'bg-rose-400', label: 'Rosa intenso' },
  { id: 'gray', value: 'bg-gray-300', label: 'Gris' },
];
